usonic : usonic.c
	clear
	gcc -Wall -std=gnu99 -pedantic -lrt -lwiringPi usonic.c -o usonic

debug : usonic.c
	clear
	gcc -Wall -std=gnu99 -pedantic -g -lrt -lwiringPi usonic.c -o usonic

clean :
	clear
	rm usonic
